### ISSUE TITLE
Missmatch of file name

### ISSUE THREAD

**Issue by dweber019** [hirsch88/generator-hirsch#1]
```javascript
events.js:85
      throw er; // Unhandled 'error' event
            ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-hirsch/app/templates/karma-shared.conf.js
    at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-hirsch/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:44:3)
    at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-hirsch/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at module.exports.yeoman.generators.Base.extend.writing.test (/usr/local/lib/node_modules/generator-hirsch/app/index.js:196:15)
    at /usr/local/lib/node_modules/generator-hirsch/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

The files are not named karma-*.conf.js. They are karma-*.config.js.
https://github.com/hirsch88/generator-hirsch/tree/master/app/templates

**Comment by hirsch88** [comment]
will be in the new release of rc2
